Re-Design
CoESS-UECal/COESS_System pull request #18
Opened 2019-11-25 15:10 UTC by kentnorca

Main Menu
>Image Changes

New Event
>Added Sliding Panel
>Change Button Style

2019-11-25 15:18 UTC, khrizthero24 commented
Change picture talaga. I dont want dat shit na.  Hahahahaha

2019-12-10 11:19 UTC, TeaRX27 commented
trying to merge 50% chance to break code

2019-12-10 12:03 UTC, TeaRX27 requested changes
- Set pnlEventImage Size to 512, 470

2019-12-10 12:03 UTC, TeaRX27 commented on System/Program.cs
> +            Application.Run(new New_Event());
```suggestion
            Application.Run(new Login());
```

2019-12-10 21:35 UTC, khrizthero24 commented
@kentnorca yung latest push mo sa branch mo wasak. @TeaRX27 pa rollback ng branch ni norca. salamat

2019-12-10 21:53 UTC, khrizthero24 commented
nevermind i may have just fucking saved the system. hahaha fucking merging

2019-12-12 20:27 UTC, kentnorca commented
mag commit muna ako? bago mag pull?

2019-12-16 14:02 UTC, merged